// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _8: x0 => x0.arrayBuffer(),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _770: x0 => x0.firstElementChild,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1089: (x0,x1) => x0.getContext(x1),
      _1091: x0 => x0.convertToBlob(),
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1286: (x0,x1) => x0.createElement(x1),
      _1292: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1293: x0 => x0.remove(),
      _1294: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1294(f,arguments.length,x0) }),
      _1295: x0 => ({createScriptURL: x0}),
      _1296: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _1297: (x0,x1,x2) => x0.createScriptURL(x1,x2),
      _1298: x0 => x0.hasChildNodes(),
      _1299: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _1300: (x0,x1) => x0.append(x1),
      _1301: (x0,x1) => x0.querySelectorAll(x1),
      _1302: (x0,x1) => x0.item(x1),
      _1303: x0 => x0.preventDefault(),
      _1304: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1304(f,arguments.length,x0) }),
      _1305: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1325: (x0,x1) => x0.createElement(x1),
      _1326: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1328: x0 => globalThis.URL.createObjectURL(x0),
      _1342: (x0,x1) => x0.appendChild(x1),
      _1358: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1358(f,arguments.length,x0,x1) }),
      _1359: x0 => globalThis.Sentry.init(x0),
      _1360: () => new Sentry.getClient(),
      _1361: x0 => x0.getOptions(),
      _1365: () => globalThis.Sentry.globalHandlersIntegration(),
      _1366: () => globalThis.Sentry.dedupeIntegration(),
      _1367: () => globalThis.Sentry.close(),
      _1368: (x0,x1) => x0.sendEnvelope(x1),
      _1371: () => globalThis.globalThis,
      _1372: x0 => x0.sdk,
      _1373: (x0,x1) => { x0.sdk = x1 },
      _1374: (x0,x1) => { x0.name = x1 },
      _1379: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1379(f,arguments.length,x0) }),
      _1380: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1380(f,arguments.length,x0) }),
      _1381: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1381(f,arguments.length,x0) }),
      _1382: (x0,x1) => x0.querySelector(x1),
      _1383: (x0,x1) => x0.replaceChildren(x1),
      _1384: x0 => x0.click(),
      _1385: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24) => ({aspectRatio: x0,background: x1,center: x2,checkCrossOrigin: x3,checkOrientation: x4,cropBoxMovable: x5,cropBoxResizable: x6,dragMode: x7,guides: x8,highlight: x9,initialAspectRatio: x10,minContainerHeight: x11,minContainerWidth: x12,minCropBoxHeight: x13,minCropBoxWidth: x14,modal: x15,movable: x16,rotatable: x17,scalable: x18,toggleDragModeOnDblclick: x19,viewMode: x20,wheelZoomRatio: x21,zoomOnTouch: x22,zoomOnWheel: x23,zoomable: x24}),
      _1386: (x0,x1) => new Cropper(x0,x1),
      _1387: () => ({}),
      _1388: (x0,x1) => x0.getCroppedCanvas(x1),
      _1389: x0 => x0.getCroppedCanvas(),
      _1390: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1390(f,arguments.length,x0) }),
      _1391: (x0,x1,x2) => x0.toBlob(x1,x2),
      _1392: (x0,x1) => x0.rotate(x1),
      _1393: (x0,x1) => x0.scale(x1),
      _1394: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1395: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1397: (x0,x1) => x0.getAttribute(x1),
      _1401: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1411: x0 => x0.close(),
      _1412: () => globalThis.PasskeyAuthenticator.init(),
      _1413: x0 => globalThis.PasskeyAuthenticator.register(x0),
      _1414: x0 => globalThis.PasskeyAuthenticator.login(x0),
      _1415: () => globalThis.PasskeyAuthenticator.cancelCurrentAuthenticatorOperation(),
      _1419: x0 => x0.decode(),
      _1420: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1421: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1422: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1422(f,arguments.length,x0) }),
      _1423: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1423(f,arguments.length,x0) }),
      _1424: x0 => x0.send(),
      _1425: () => new XMLHttpRequest(),
      _1426: (x0,x1) => x0.query(x1),
      _1427: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1427(f,arguments.length,x0) }),
      _1428: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1428(f,arguments.length,x0) }),
      _1429: (x0,x1,x2) => ({enableHighAccuracy: x0,timeout: x1,maximumAge: x2}),
      _1430: (x0,x1,x2,x3) => x0.getCurrentPosition(x1,x2,x3),
      _1435: (x0,x1) => x0.getItem(x1),
      _1436: (x0,x1) => x0.removeItem(x1),
      _1437: (x0,x1,x2) => x0.setItem(x1,x2),
      _1438: x0 => ({name: x0}),
      _1439: x0 => ({audio: x0}),
      _1440: (x0,x1) => x0.getUserMedia(x1),
      _1441: x0 => x0.getAudioTracks(),
      _1442: x0 => x0.stop(),
      _1443: x0 => ({video: x0}),
      _1444: x0 => x0.getVideoTracks(),
      _1445: () => globalThis.Notification.requestPermission(),
      _1446: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1446(f,arguments.length,x0) }),
      _1447: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1447(f,arguments.length,x0) }),
      _1448: (x0,x1,x2) => x0.getCurrentPosition(x1,x2),
      _1455: (x0,x1,x2,x3,x4,x5,x6,x7) => ({apiKey: x0,authDomain: x1,databaseURL: x2,projectId: x3,storageBucket: x4,messagingSenderId: x5,measurementId: x6,appId: x7}),
      _1456: (x0,x1) => globalThis.firebase_core.initializeApp(x0,x1),
      _1458: () => globalThis.firebase_core.getApp(),
      _1459: (x0,x1,x2) => globalThis.firebase_core.registerVersion(x0,x1,x2),
      _1461: () => globalThis.firebase_core.SDK_VERSION,
      _1467: x0 => x0.apiKey,
      _1469: x0 => x0.authDomain,
      _1471: x0 => x0.databaseURL,
      _1473: x0 => x0.projectId,
      _1475: x0 => x0.storageBucket,
      _1477: x0 => x0.messagingSenderId,
      _1479: x0 => x0.measurementId,
      _1481: x0 => x0.appId,
      _1483: x0 => x0.name,
      _1484: x0 => x0.options,
      _1485: (x0,x1) => x0.debug(x1),
      _1486: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1486(f,arguments.length,x0) }),
      _1487: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1487(f,arguments.length,x0,x1) }),
      _1488: (x0,x1) => ({createScript: x0,createScriptURL: x1}),
      _1489: (x0,x1) => x0.createScriptURL(x1),
      _1490: (x0,x1,x2) => x0.createScript(x1,x2),
      _1491: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1491(f,arguments.length,x0) }),
      _1492: x0 => x0.deviceMemory,
      _1493: (x0,x1) => x0.key(x1),
      _1494: (x0,x1,x2,x3,x4,x5,x6,x7) => x0.unwrapKey(x1,x2,x3,x4,x5,x6,x7),
      _1495: (x0,x1,x2,x3,x4,x5) => x0.importKey(x1,x2,x3,x4,x5),
      _1496: (x0,x1,x2,x3) => x0.generateKey(x1,x2,x3),
      _1497: (x0,x1,x2,x3,x4) => x0.wrapKey(x1,x2,x3,x4),
      _1498: (x0,x1,x2) => x0.exportKey(x1,x2),
      _1499: (x0,x1) => x0.getRandomValues(x1),
      _1500: (x0,x1,x2,x3) => x0.encrypt(x1,x2,x3),
      _1501: (x0,x1,x2,x3) => x0.decrypt(x1,x2,x3),
      _1502: () => globalThis.removeSplashFromWeb(),
      _1505: (x0,x1) => x0.initialize(x1),
      _1509: x0 => x0.disableAutoSelect(),
      _1510: Date.now,
      _1511: secondsSinceEpoch => {
        const date = new Date(secondsSinceEpoch * 1000);
        const match = /\((.*)\)/.exec(date.toString());
        if (match == null) {
            // This should never happen on any recent browser.
            return '';
        }
        return match[1];
      },
      _1512: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1513: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1514: () => new Error().stack,
      _1515: () => typeof dartUseDateNowForTicks !== "undefined",
      _1516: () => 1000 * performance.now(),
      _1517: () => Date.now(),
      _1518: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1519: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1520: () => new WeakMap(),
      _1521: (map, o) => map.get(o),
      _1522: (map, o, v) => map.set(o, v),
      _1523: (exn) => exn.toString(),
      _1524: (exn) => exn.stack,
      _1525: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1526: x0 => new WeakRef(x0),
      _1527: x0 => x0.deref(),
      _1534: () => globalThis.WeakRef,
      _1538: s => JSON.stringify(s),
      _1539: s => printToConsole(s),
      _1540: (o, p, r) => o.replaceAll(p, () => r),
      _1541: (o, p, r) => o.replace(p, () => r),
      _1542: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1543: s => s.toUpperCase(),
      _1544: s => s.trim(),
      _1545: s => s.trimLeft(),
      _1546: s => s.trimRight(),
      _1547: (string, times) => string.repeat(times),
      _1548: Function.prototype.call.bind(String.prototype.indexOf),
      _1549: (s, p, i) => s.lastIndexOf(p, i),
      _1550: (string, token) => string.split(token),
      _1551: Object.is,
      _1554: (o, t) => typeof o === t,
      _1555: (o, c) => o instanceof c,
      _1556: o => Object.keys(o),
      _1586: x0 => new Array(x0),
      _1588: x0 => x0.length,
      _1590: (x0,x1) => x0[x1],
      _1591: (x0,x1,x2) => { x0[x1] = x2 },
      _1594: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1596: x0 => new Int8Array(x0),
      _1597: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1599: x0 => new Uint8ClampedArray(x0),
      _1601: x0 => new Int16Array(x0),
      _1603: x0 => new Uint16Array(x0),
      _1605: x0 => new Int32Array(x0),
      _1607: x0 => new Uint32Array(x0),
      _1609: x0 => new Float32Array(x0),
      _1611: x0 => new Float64Array(x0),
      _1635: x0 => x0.random(),
      _1636: (x0,x1) => x0.getRandomValues(x1),
      _1637: () => globalThis.crypto,
      _1638: () => globalThis.Math,
      _1651: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1652: (handle) => clearTimeout(handle),
      _1653: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1654: (handle) => clearInterval(handle),
      _1655: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1656: () => Date.now(),
      _1657: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1658: (x0,x1) => x0.exec(x1),
      _1659: (x0,x1) => x0.test(x1),
      _1660: x0 => x0.pop(),
      _1662: o => o === undefined,
      _1664: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1666: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1667: o => o instanceof RegExp,
      _1668: (l, r) => l === r,
      _1669: o => o,
      _1670: o => o,
      _1671: o => o,
      _1672: b => !!b,
      _1673: o => o.length,
      _1675: (o, i) => o[i],
      _1676: f => f.dartFunction,
      _1677: () => ({}),
      _1678: () => [],
      _1680: () => globalThis,
      _1681: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1682: (o, p) => p in o,
      _1683: (o, p) => o[p],
      _1684: (o, p, v) => o[p] = v,
      _1685: (o, m, a) => o[m].apply(o, a),
      _1687: o => String(o),
      _1688: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1689: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1689(f,arguments.length,x0) }),
      _1690: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1690(f,arguments.length,x0,x1) }),
      _1691: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1692: o => [o],
      _1693: (o0, o1) => [o0, o1],
      _1694: (o0, o1, o2) => [o0, o1, o2],
      _1695: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1696: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1697: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1698: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1699: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1700: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1701: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1702: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1703: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1704: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1705: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1706: x0 => new ArrayBuffer(x0),
      _1707: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1708: x0 => x0.input,
      _1709: x0 => x0.index,
      _1710: x0 => x0.groups,
      _1711: x0 => x0.flags,
      _1712: x0 => x0.multiline,
      _1713: x0 => x0.ignoreCase,
      _1714: x0 => x0.unicode,
      _1715: x0 => x0.dotAll,
      _1716: (x0,x1) => { x0.lastIndex = x1 },
      _1717: (o, p) => p in o,
      _1718: (o, p) => o[p],
      _1719: (o, p, v) => o[p] = v,
      _1720: (o, p) => delete o[p],
      _1721: x0 => globalThis.Object.keys(x0),
      _1723: x0 => new Date(x0),
      _1725: x0 => x0.getTime(),
      _1726: x0 => x0.length,
      _1727: x0 => x0.message,
      _1728: x0 => x0.name,
      _1732: x0 => x0.delete(),
      _1733: x0 => x0.continue(),
      _1736: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1736(f,arguments.length,x0) }),
      _1737: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1737(f,arguments.length,x0) }),
      _1748: (x0,x1) => x0.getKey(x1),
      _1754: x0 => x0.openCursor(),
      _1757: (x0,x1) => ({unique: x0,multiEntry: x1}),
      _1758: (x0,x1,x2,x3) => x0.createIndex(x1,x2,x3),
      _1760: (x0,x1) => x0.add(x1),
      _1762: (x0,x1) => x0.get(x1),
      _1765: (x0,x1) => x0.put(x1),
      _1766: (x0,x1,x2) => x0.put(x1,x2),
      _1767: (x0,x1) => x0.delete(x1),
      _1768: (x0,x1) => x0.index(x1),
      _1769: x0 => x0.openCursor(),
      _1770: (x0,x1) => x0.openCursor(x1),
      _1776: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1776(f,arguments.length,x0) }),
      _1777: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1777(f,arguments.length,x0) }),
      _1778: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1778(f,arguments.length,x0) }),
      _1779: (x0,x1) => x0.objectStore(x1),
      _1781: (x0,x1) => ({keyPath: x0,autoIncrement: x1}),
      _1782: (x0,x1,x2) => x0.createObjectStore(x1,x2),
      _1783: (x0,x1,x2) => x0.transaction(x1,x2),
      _1784: x0 => x0.close(),
      _1787: (x0,x1,x2) => x0.open(x1,x2),
      _1788: (x0,x1) => x0.open(x1),
      _1790: (x0,x1) => x0.deleteDatabase(x1),
      _1793: (x0,x1) => x0.postMessage(x1),
      _1794: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1794(f,arguments.length,x0) }),
      _1795: x0 => new BroadcastChannel(x0),
      _1797: (x0,x1) => globalThis.IDBKeyRange.lowerBound(x0,x1),
      _1798: (x0,x1) => globalThis.IDBKeyRange.upperBound(x0,x1),
      _1804: (x0,x1) => x0.item(x1),
      _1805: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1805(f,arguments.length,x0) }),
      _1806: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1806(f,arguments.length,x0) }),
      _4430: () => new XMLHttpRequest(),
      _4431: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _4435: x0 => x0.send(),
      _4437: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4437(f,arguments.length,x0) }),
      _4438: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4438(f,arguments.length,x0) }),
      _4447: x0 => x0.deviceMemory,
      _4448: (x0,x1) => x0.matchMedia(x1),
      _4458: () => new AbortController(),
      _4459: x0 => x0.abort(),
      _4460: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _4461: (x0,x1) => globalThis.fetch(x0,x1),
      _4462: (x0,x1) => x0.get(x1),
      _4463: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._4463(f,arguments.length,x0,x1,x2) }),
      _4464: (x0,x1) => x0.forEach(x1),
      _4465: x0 => x0.getReader(),
      _4466: x0 => x0.cancel(),
      _4467: x0 => x0.read(),
      _4468: x0 => x0.trustedTypes,
      _4469: (x0,x1) => { x0.src = x1 },
      _4470: (x0,x1) => x0.createScriptURL(x1),
      _4471: x0 => x0.nonce,
      _4472: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4472(f,arguments.length,x0) }),
      _4474: (x0,x1) => x0.item(x1),
      _4656: (x0,x1) => { x0.fillColor = x1 },
      _4698: x0 => x0.trustedTypes,
      _4699: (x0,x1) => { x0.text = x1 },
      _4700: o => o instanceof Array,
      _4701: (a, i) => a.push(i),
      _4704: (a, l) => a.length = l,
      _4705: a => a.pop(),
      _4706: (a, i) => a.splice(i, 1),
      _4707: (a, s) => a.join(s),
      _4708: (a, s, e) => a.slice(s, e),
      _4710: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _4711: a => a.length,
      _4712: (a, l) => a.length = l,
      _4713: (a, i) => a[i],
      _4714: (a, i, v) => a[i] = v,
      _4716: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _4717: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _4719: o => o instanceof Uint8Array,
      _4720: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _4721: o => o instanceof Int8Array,
      _4722: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _4723: o => o instanceof Uint8ClampedArray,
      _4724: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _4725: o => o instanceof Uint16Array,
      _4726: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _4727: o => o instanceof Int16Array,
      _4728: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _4729: o => o instanceof Uint32Array,
      _4730: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _4731: o => o instanceof Int32Array,
      _4732: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _4734: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _4735: o => o instanceof Float32Array,
      _4736: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _4737: o => o instanceof Float64Array,
      _4738: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _4739: (t, s) => t.set(s),
      _4740: l => new DataView(new ArrayBuffer(l)),
      _4741: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _4743: o => o.buffer,
      _4744: o => o.byteOffset,
      _4745: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _4746: (b, o) => new DataView(b, o),
      _4747: (b, o, l) => new DataView(b, o, l),
      _4748: Function.prototype.call.bind(DataView.prototype.getUint8),
      _4749: Function.prototype.call.bind(DataView.prototype.setUint8),
      _4750: Function.prototype.call.bind(DataView.prototype.getInt8),
      _4751: Function.prototype.call.bind(DataView.prototype.setInt8),
      _4752: Function.prototype.call.bind(DataView.prototype.getUint16),
      _4753: Function.prototype.call.bind(DataView.prototype.setUint16),
      _4754: Function.prototype.call.bind(DataView.prototype.getInt16),
      _4755: Function.prototype.call.bind(DataView.prototype.setInt16),
      _4756: Function.prototype.call.bind(DataView.prototype.getUint32),
      _4757: Function.prototype.call.bind(DataView.prototype.setUint32),
      _4758: Function.prototype.call.bind(DataView.prototype.getInt32),
      _4759: Function.prototype.call.bind(DataView.prototype.setInt32),
      _4762: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _4763: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _4764: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _4765: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _4766: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _4767: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _4768: Function.prototype.call.bind(Number.prototype.toString),
      _4769: Function.prototype.call.bind(BigInt.prototype.toString),
      _4770: Function.prototype.call.bind(Number.prototype.toString),
      _4771: (d, digits) => d.toFixed(digits),
      _4811: x0 => globalThis.dmovelDownloadAsset(x0),
      _4870: () => globalThis.document,
      _4876: (x0,x1) => { x0.height = x1 },
      _4878: (x0,x1) => { x0.width = x1 },
      _4880: (x0,x1) => { x0.pointerEvents = x1 },
      _4889: x0 => x0.style,
      _4892: x0 => x0.src,
      _4893: (x0,x1) => { x0.src = x1 },
      _4894: x0 => x0.naturalWidth,
      _4895: x0 => x0.naturalHeight,
      _4911: x0 => x0.status,
      _4912: (x0,x1) => { x0.responseType = x1 },
      _4914: x0 => x0.response,
      _4915: () => globalThis.dmovelGetCredential(),
      _4916: x0 => globalThis.dmovelCredentialId(x0),
      _4917: x0 => globalThis.dmovelCredentialPassword(x0),
      _4918: (x0,x1) => globalThis.dmovelStoreCredential(x0,x1),
      _4919: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._4919(f,arguments.length,x0,x1) }),
      _4920: () => globalThis.dmovelInitAutofill(),
      _4921: () => globalThis.dmovelGetPendingAutofill(),
      _4922: () => globalThis.dmovelStopAutofill(),
      _4923: (x0,x1) => globalThis.dmovelSetAutofillValues(x0,x1),
      _4924: () => globalThis.dmovelSubmitAutofillForm(),
      _4925: x0 => { globalThis.onDmovelAutofillChanged = x0 },
      _4926: x0 => x0.email,
      _4927: x0 => x0.password,
      _4929: () => globalThis.loadCropper(),
      _4930: () => globalThis.google.accounts.oauth2,
      _4932: (x0,x1) => x0.revoke(x1),
      _4933: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4933(f,arguments.length,x0) }),
      _4934: (x0,x1,x2) => x0.revoke(x1,x2),
      _4950: x0 => x0.access_token,
      _4965: () => globalThis.google.accounts.id,
      _4979: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4979(f,arguments.length,x0) }),
      _4982: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16) => ({client_id: x0,auto_select: x1,callback: x2,login_uri: x3,native_callback: x4,cancel_on_tap_outside: x5,prompt_parent_id: x6,nonce: x7,context: x8,state_cookie_domain: x9,ux_mode: x10,allowed_parent_origin: x11,intermediate_iframe_close_callback: x12,itp_support: x13,login_hint: x14,hd: x15,use_fedcm_for_prompt: x16}),
      _4993: x0 => x0.error,
      _4995: x0 => x0.credential,
      _5006: x0 => { globalThis.onGoogleLibraryLoad = x0 },
      _5007: (module,f) => finalizeWrapper(f, function() { return module.exports._5007(f,arguments.length) }),
      _5058: (x0,x1) => { x0.responseType = x1 },
      _5059: x0 => x0.response,
      _5095: x0 => x0.length,
      _5134: x0 => x0.style,
      _5147: (x0,x1) => { x0.oncancel = x1 },
      _5153: (x0,x1) => { x0.onchange = x1 },
      _5193: (x0,x1) => { x0.onerror = x1 },
      _5333: (x0,x1) => { x0.nonce = x1 },
      _5566: (x0,x1) => { x0.src = x1 },
      _6063: (x0,x1) => { x0.accept = x1 },
      _6077: x0 => x0.files,
      _6103: (x0,x1) => { x0.multiple = x1 },
      _6121: (x0,x1) => { x0.type = x1 },
      _6371: (x0,x1) => { x0.src = x1 },
      _6373: (x0,x1) => { x0.type = x1 },
      _6377: (x0,x1) => { x0.async = x1 },
      _6379: (x0,x1) => { x0.defer = x1 },
      _6381: (x0,x1) => { x0.crossOrigin = x1 },
      _6383: (x0,x1) => { x0.text = x1 },
      _6385: (x0,x1) => { x0.integrity = x1 },
      _6838: () => globalThis.window,
      _6842: (x0,x1) => x0[x1],
      _6876: x0 => x0.document,
      _6879: x0 => x0.location,
      _6898: x0 => x0.navigator,
      _6902: x0 => x0.screen,
      _6914: x0 => x0.devicePixelRatio,
      _7153: x0 => x0.isSecureContext,
      _7155: x0 => x0.indexedDB,
      _7156: x0 => x0.crypto,
      _7160: x0 => x0.trustedTypes,
      _7161: x0 => x0.sessionStorage,
      _7162: x0 => x0.localStorage,
      _7172: x0 => x0.origin,
      _7181: x0 => x0.pathname,
      _7268: x0 => x0.geolocation,
      _7271: x0 => x0.mediaDevices,
      _7273: x0 => x0.permissions,
      _7274: x0 => x0.maxTouchPoints,
      _7281: x0 => x0.appCodeName,
      _7282: x0 => x0.appName,
      _7283: x0 => x0.appVersion,
      _7284: x0 => x0.platform,
      _7285: x0 => x0.product,
      _7286: x0 => x0.productSub,
      _7287: x0 => x0.userAgent,
      _7288: x0 => x0.vendor,
      _7289: x0 => x0.vendorSub,
      _7291: x0 => x0.language,
      _7292: x0 => x0.languages,
      _7293: x0 => x0.onLine,
      _7298: x0 => x0.hardwareConcurrency,
      _7337: x0 => x0.data,
      _7385: (x0,x1) => { x0.onmessage = x1 },
      _7492: x0 => x0.length,
      _9396: x0 => x0.type,
      _9397: x0 => x0.target,
      _9437: x0 => x0.signal,
      _9446: x0 => x0.length,
      _9486: x0 => x0.baseURI,
      _9492: x0 => x0.firstChild,
      _9503: () => globalThis.document,
      _9584: x0 => x0.body,
      _9586: x0 => x0.head,
      _9915: (x0,x1) => { x0.id = x1 },
      _11261: x0 => x0.value,
      _11263: x0 => x0.done,
      _11443: x0 => x0.size,
      _11444: x0 => x0.type,
      _11451: x0 => x0.name,
      _11452: x0 => x0.lastModified,
      _11457: x0 => x0.length,
      _11960: x0 => x0.url,
      _11962: x0 => x0.status,
      _11964: x0 => x0.statusText,
      _11965: x0 => x0.headers,
      _11966: x0 => x0.body,
      _12233: x0 => x0.type,
      _12248: x0 => x0.matches,
      _12259: x0 => x0.availWidth,
      _12260: x0 => x0.availHeight,
      _12265: x0 => x0.orientation,
      _12351: x0 => x0.state,
      _12752: x0 => x0.active,
      _13415: x0 => x0.result,
      _13416: x0 => x0.error,
      _13421: (x0,x1) => { x0.onsuccess = x1 },
      _13423: (x0,x1) => { x0.onerror = x1 },
      _13429: x0 => x0.oldVersion,
      _13443: x0 => x0.name,
      _13445: x0 => x0.objectStoreNames,
      _13461: x0 => x0.name,
      _13463: x0 => x0.keyPath,
      _13466: x0 => x0.autoIncrement,
      _13471: x0 => x0.name,
      _13474: x0 => x0.keyPath,
      _13475: x0 => x0.multiEntry,
      _13476: x0 => x0.unique,
      _13486: x0 => x0.key,
      _13487: x0 => x0.primaryKey,
      _13489: x0 => x0.value,
      _13495: x0 => x0.error,
      _13497: (x0,x1) => { x0.onabort = x1 },
      _13499: (x0,x1) => { x0.oncomplete = x1 },
      _13501: (x0,x1) => { x0.onerror = x1 },
      _13626: x0 => x0.coords,
      _13627: x0 => x0.timestamp,
      _13629: x0 => x0.accuracy,
      _13630: x0 => x0.latitude,
      _13631: x0 => x0.longitude,
      _13632: x0 => x0.altitude,
      _13633: x0 => x0.altitudeAccuracy,
      _13634: x0 => x0.heading,
      _13635: x0 => x0.speed,
      _13636: x0 => x0.code,
      _13637: x0 => x0.message,
      _14323: (x0,x1) => { x0.display = x1 },
      _14487: (x0,x1) => { x0.height = x1 },
      _14659: (x0,x1) => { x0.maxWidth = x1 },
      _15177: (x0,x1) => { x0.width = x1 },
      _15545: x0 => x0.name,
      _15546: x0 => x0.message,
      _15549: x0 => x0.subtle,
      _16252: () => globalThis.console,
      _16275: () => globalThis.window.flutterCanvasKit,
      _16276: () => globalThis.window._flutter_skwasmInstance,
      _16277: () => globalThis.dmovelLoader.markFlutterReady(),
      _16278: () => globalThis.triggerPwaInstall(),
      _16279: () => globalThis.isPwaInstallAvailable(),
      _16280: () => globalThis.isPwaInstalled(),
      _16281: () => globalThis.getPwaHostPlatform(),
      _16283: x0 => x0.name,
      _16284: x0 => x0.message,
      _16285: x0 => x0.code,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
!function(){try{var e="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof globalThis?globalThis:"undefined"!=typeof self?self:{},n=(new e.Error).stack;n&&(e._sentryDebugIds=e._sentryDebugIds||{},e._sentryDebugIds[n]="5a95c0d2-99e9-5f4e-aa63-18157327d340")}catch(e){}}();
//# debugId=5a95c0d2-99e9-5f4e-aa63-18157327d340
