// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _8: x0 => x0.arrayBuffer(),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _770: x0 => x0.firstElementChild,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1089: (x0,x1) => x0.getContext(x1),
      _1091: x0 => x0.convertToBlob(),
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1286: (x0,x1) => x0.createElement(x1),
      _1292: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1293: x0 => x0.remove(),
      _1294: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1294(f,arguments.length,x0) }),
      _1295: x0 => ({createScriptURL: x0}),
      _1296: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _1297: (x0,x1,x2) => x0.createScriptURL(x1,x2),
      _1298: x0 => x0.hasChildNodes(),
      _1299: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _1300: (x0,x1) => x0.append(x1),
      _1301: (x0,x1) => x0.querySelectorAll(x1),
      _1302: (x0,x1) => x0.item(x1),
      _1303: x0 => x0.preventDefault(),
      _1304: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1304(f,arguments.length,x0) }),
      _1305: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1325: (x0,x1) => x0.createElement(x1),
      _1326: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1328: x0 => globalThis.URL.createObjectURL(x0),
      _1342: (x0,x1) => x0.appendChild(x1),
      _1358: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1358(f,arguments.length,x0,x1) }),
      _1359: x0 => globalThis.Sentry.init(x0),
      _1360: () => new Sentry.getClient(),
      _1361: x0 => x0.getOptions(),
      _1365: () => globalThis.Sentry.globalHandlersIntegration(),
      _1366: () => globalThis.Sentry.dedupeIntegration(),
      _1367: () => globalThis.Sentry.close(),
      _1368: (x0,x1) => x0.sendEnvelope(x1),
      _1371: () => globalThis.globalThis,
      _1372: x0 => x0.sdk,
      _1373: (x0,x1) => { x0.sdk = x1 },
      _1374: (x0,x1) => { x0.name = x1 },
      _1379: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1379(f,arguments.length,x0) }),
      _1380: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1380(f,arguments.length,x0) }),
      _1381: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1381(f,arguments.length,x0) }),
      _1382: (x0,x1) => x0.querySelector(x1),
      _1383: (x0,x1) => x0.replaceChildren(x1),
      _1384: x0 => x0.click(),
      _1394: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1395: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1397: (x0,x1) => x0.getAttribute(x1),
      _1398: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1398(f,arguments.length,x0) }),
      _1399: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1399(f,arguments.length,x0) }),
      _1400: (x0,x1) => x0.closest(x1),
      _1401: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1402: x0 => x0.disconnect(),
      _1403: x0 => x0.disconnect(),
      _1404: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1404(f,arguments.length,x0,x1) }),
      _1405: x0 => new ResizeObserver(x0),
      _1406: (x0,x1) => x0.observe(x1),
      _1407: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1407(f,arguments.length,x0,x1) }),
      _1408: x0 => new MutationObserver(x0),
      _1409: x0 => ({childList: x0}),
      _1410: (x0,x1,x2) => x0.observe(x1,x2),
      _1411: x0 => x0.close(),
      _1412: () => globalThis.PasskeyAuthenticator.init(),
      _1413: x0 => globalThis.PasskeyAuthenticator.register(x0),
      _1414: x0 => globalThis.PasskeyAuthenticator.login(x0),
      _1417: () => globalThis.PasskeyAuthenticator.cancelCurrentAuthenticatorOperation(),
      _1421: x0 => x0.decode(),
      _1422: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1423: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1424: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1424(f,arguments.length,x0) }),
      _1425: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1425(f,arguments.length,x0) }),
      _1426: x0 => x0.send(),
      _1427: () => new XMLHttpRequest(),
      _1428: (x0,x1) => x0.query(x1),
      _1429: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1429(f,arguments.length,x0) }),
      _1430: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1430(f,arguments.length,x0) }),
      _1431: (x0,x1,x2) => ({enableHighAccuracy: x0,timeout: x1,maximumAge: x2}),
      _1432: (x0,x1,x2,x3) => x0.getCurrentPosition(x1,x2,x3),
      _1437: (x0,x1) => x0.getItem(x1),
      _1438: (x0,x1) => x0.removeItem(x1),
      _1439: (x0,x1,x2) => x0.setItem(x1,x2),
      _1457: x0 => ({name: x0}),
      _1458: x0 => ({audio: x0}),
      _1459: (x0,x1) => x0.getUserMedia(x1),
      _1460: x0 => x0.getAudioTracks(),
      _1461: x0 => x0.stop(),
      _1462: x0 => ({video: x0}),
      _1463: x0 => x0.getVideoTracks(),
      _1464: () => globalThis.Notification.requestPermission(),
      _1465: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1465(f,arguments.length,x0) }),
      _1466: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1466(f,arguments.length,x0) }),
      _1467: (x0,x1,x2) => x0.getCurrentPosition(x1,x2),
      _1474: (x0,x1,x2,x3,x4,x5,x6,x7) => ({apiKey: x0,authDomain: x1,databaseURL: x2,projectId: x3,storageBucket: x4,messagingSenderId: x5,measurementId: x6,appId: x7}),
      _1475: (x0,x1) => globalThis.firebase_core.initializeApp(x0,x1),
      _1477: () => globalThis.firebase_core.getApp(),
      _1478: (x0,x1,x2) => globalThis.firebase_core.registerVersion(x0,x1,x2),
      _1480: () => globalThis.firebase_core.SDK_VERSION,
      _1486: x0 => x0.apiKey,
      _1488: x0 => x0.authDomain,
      _1490: x0 => x0.databaseURL,
      _1492: x0 => x0.projectId,
      _1494: x0 => x0.storageBucket,
      _1496: x0 => x0.messagingSenderId,
      _1498: x0 => x0.measurementId,
      _1500: x0 => x0.appId,
      _1502: x0 => x0.name,
      _1503: x0 => x0.options,
      _1504: (x0,x1) => x0.debug(x1),
      _1505: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1505(f,arguments.length,x0) }),
      _1506: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1506(f,arguments.length,x0,x1) }),
      _1507: (x0,x1) => ({createScript: x0,createScriptURL: x1}),
      _1508: (x0,x1) => x0.createScriptURL(x1),
      _1509: (x0,x1,x2) => x0.createScript(x1,x2),
      _1510: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1510(f,arguments.length,x0) }),
      _1511: x0 => x0.deviceMemory,
      _1512: (x0,x1) => x0.key(x1),
      _1513: (x0,x1,x2,x3,x4,x5,x6,x7) => x0.unwrapKey(x1,x2,x3,x4,x5,x6,x7),
      _1514: (x0,x1,x2,x3,x4,x5) => x0.importKey(x1,x2,x3,x4,x5),
      _1515: (x0,x1,x2,x3) => x0.generateKey(x1,x2,x3),
      _1516: (x0,x1,x2,x3,x4) => x0.wrapKey(x1,x2,x3,x4),
      _1517: (x0,x1,x2) => x0.exportKey(x1,x2),
      _1518: (x0,x1) => x0.getRandomValues(x1),
      _1519: (x0,x1,x2,x3) => x0.encrypt(x1,x2,x3),
      _1520: (x0,x1,x2,x3) => x0.decrypt(x1,x2,x3),
      _1521: () => globalThis.removeSplashFromWeb(),
      _1524: (x0,x1) => x0.initialize(x1),
      _1528: x0 => x0.disableAutoSelect(),
      _1529: Date.now,
      _1530: secondsSinceEpoch => {
        const date = new Date(secondsSinceEpoch * 1000);
        const match = /\((.*)\)/.exec(date.toString());
        if (match == null) {
            // This should never happen on any recent browser.
            return '';
        }
        return match[1];
      },
      _1531: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1532: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1533: () => new Error().stack,
      _1534: () => typeof dartUseDateNowForTicks !== "undefined",
      _1535: () => 1000 * performance.now(),
      _1536: () => Date.now(),
      _1537: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1538: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1539: () => new WeakMap(),
      _1540: (map, o) => map.get(o),
      _1541: (map, o, v) => map.set(o, v),
      _1542: (exn) => exn.toString(),
      _1543: (exn) => exn.stack,
      _1544: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1545: x0 => new WeakRef(x0),
      _1546: x0 => x0.deref(),
      _1553: () => globalThis.WeakRef,
      _1557: s => JSON.stringify(s),
      _1558: s => printToConsole(s),
      _1559: (o, p, r) => o.replaceAll(p, () => r),
      _1560: (o, p, r) => o.replace(p, () => r),
      _1561: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1562: s => s.toUpperCase(),
      _1563: s => s.trim(),
      _1564: s => s.trimLeft(),
      _1565: s => s.trimRight(),
      _1566: (string, times) => string.repeat(times),
      _1567: Function.prototype.call.bind(String.prototype.indexOf),
      _1568: (s, p, i) => s.lastIndexOf(p, i),
      _1569: (string, token) => string.split(token),
      _1570: Object.is,
      _1573: (o, t) => typeof o === t,
      _1574: (o, c) => o instanceof c,
      _1575: o => Object.keys(o),
      _1605: x0 => new Array(x0),
      _1607: x0 => x0.length,
      _1609: (x0,x1) => x0[x1],
      _1610: (x0,x1,x2) => { x0[x1] = x2 },
      _1613: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1615: x0 => new Int8Array(x0),
      _1616: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1618: x0 => new Uint8ClampedArray(x0),
      _1620: x0 => new Int16Array(x0),
      _1622: x0 => new Uint16Array(x0),
      _1624: x0 => new Int32Array(x0),
      _1626: x0 => new Uint32Array(x0),
      _1628: x0 => new Float32Array(x0),
      _1630: x0 => new Float64Array(x0),
      _1654: x0 => x0.random(),
      _1655: (x0,x1) => x0.getRandomValues(x1),
      _1656: () => globalThis.crypto,
      _1657: () => globalThis.Math,
      _1670: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1671: (handle) => clearTimeout(handle),
      _1672: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1673: (handle) => clearInterval(handle),
      _1674: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1675: () => Date.now(),
      _1676: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1677: (x0,x1) => x0.exec(x1),
      _1678: (x0,x1) => x0.test(x1),
      _1679: x0 => x0.pop(),
      _1681: o => o === undefined,
      _1683: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1685: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1686: o => o instanceof RegExp,
      _1687: (l, r) => l === r,
      _1688: o => o,
      _1689: o => o,
      _1690: o => o,
      _1691: b => !!b,
      _1692: o => o.length,
      _1694: (o, i) => o[i],
      _1695: f => f.dartFunction,
      _1696: () => ({}),
      _1697: () => [],
      _1699: () => globalThis,
      _1700: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1701: (o, p) => p in o,
      _1702: (o, p) => o[p],
      _1703: (o, p, v) => o[p] = v,
      _1704: (o, m, a) => o[m].apply(o, a),
      _1706: o => String(o),
      _1707: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1708: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1708(f,arguments.length,x0) }),
      _1709: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1709(f,arguments.length,x0,x1) }),
      _1710: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1711: o => [o],
      _1712: (o0, o1) => [o0, o1],
      _1713: (o0, o1, o2) => [o0, o1, o2],
      _1714: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1715: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1716: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1717: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1718: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1719: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1720: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1721: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1722: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1723: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1724: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1725: x0 => new ArrayBuffer(x0),
      _1726: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1727: x0 => x0.input,
      _1728: x0 => x0.index,
      _1729: x0 => x0.groups,
      _1730: x0 => x0.flags,
      _1731: x0 => x0.multiline,
      _1732: x0 => x0.ignoreCase,
      _1733: x0 => x0.unicode,
      _1734: x0 => x0.dotAll,
      _1735: (x0,x1) => { x0.lastIndex = x1 },
      _1736: (o, p) => p in o,
      _1737: (o, p) => o[p],
      _1738: (o, p, v) => o[p] = v,
      _1739: (o, p) => delete o[p],
      _1740: x0 => globalThis.Object.keys(x0),
      _1742: x0 => new Date(x0),
      _1744: x0 => x0.getTime(),
      _1745: x0 => x0.length,
      _1746: x0 => x0.message,
      _1747: x0 => x0.name,
      _1751: x0 => x0.delete(),
      _1752: x0 => x0.continue(),
      _1755: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1755(f,arguments.length,x0) }),
      _1756: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1756(f,arguments.length,x0) }),
      _1767: (x0,x1) => x0.getKey(x1),
      _1773: x0 => x0.openCursor(),
      _1776: (x0,x1) => ({unique: x0,multiEntry: x1}),
      _1777: (x0,x1,x2,x3) => x0.createIndex(x1,x2,x3),
      _1779: (x0,x1) => x0.add(x1),
      _1781: (x0,x1) => x0.get(x1),
      _1784: (x0,x1) => x0.put(x1),
      _1785: (x0,x1,x2) => x0.put(x1,x2),
      _1786: (x0,x1) => x0.delete(x1),
      _1787: (x0,x1) => x0.index(x1),
      _1788: x0 => x0.openCursor(),
      _1789: (x0,x1) => x0.openCursor(x1),
      _1795: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1795(f,arguments.length,x0) }),
      _1796: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1796(f,arguments.length,x0) }),
      _1797: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1797(f,arguments.length,x0) }),
      _1798: (x0,x1) => x0.objectStore(x1),
      _1800: (x0,x1) => ({keyPath: x0,autoIncrement: x1}),
      _1801: (x0,x1,x2) => x0.createObjectStore(x1,x2),
      _1802: (x0,x1,x2) => x0.transaction(x1,x2),
      _1803: x0 => x0.close(),
      _1806: (x0,x1,x2) => x0.open(x1,x2),
      _1807: (x0,x1) => x0.open(x1),
      _1809: (x0,x1) => x0.deleteDatabase(x1),
      _1812: (x0,x1) => x0.postMessage(x1),
      _1813: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1813(f,arguments.length,x0) }),
      _1814: x0 => new BroadcastChannel(x0),
      _1816: (x0,x1) => globalThis.IDBKeyRange.lowerBound(x0,x1),
      _1817: (x0,x1) => globalThis.IDBKeyRange.upperBound(x0,x1),
      _1823: (x0,x1) => x0.item(x1),
      _1824: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1824(f,arguments.length,x0) }),
      _1825: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1825(f,arguments.length,x0) }),
      _4457: () => new XMLHttpRequest(),
      _4458: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _4462: x0 => x0.send(),
      _4464: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4464(f,arguments.length,x0) }),
      _4465: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4465(f,arguments.length,x0) }),
      _4471: x0 => ({type: x0}),
      _4472: (x0,x1) => new Blob(x0,x1),
      _4476: x0 => x0.deviceMemory,
      _4477: (x0,x1) => x0.matchMedia(x1),
      _4481: () => new FileReader(),
      _4482: (x0,x1) => x0.readAsArrayBuffer(x1),
      _4485: () => new AbortController(),
      _4486: x0 => x0.abort(),
      _4487: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _4488: (x0,x1) => globalThis.fetch(x0,x1),
      _4489: (x0,x1) => x0.get(x1),
      _4490: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._4490(f,arguments.length,x0,x1,x2) }),
      _4491: (x0,x1) => x0.forEach(x1),
      _4492: x0 => x0.getReader(),
      _4493: x0 => x0.cancel(),
      _4494: x0 => x0.read(),
      _4495: x0 => x0.trustedTypes,
      _4496: (x0,x1) => { x0.src = x1 },
      _4497: (x0,x1) => x0.createScriptURL(x1),
      _4498: x0 => x0.nonce,
      _4499: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4499(f,arguments.length,x0) }),
      _4501: (x0,x1) => x0.item(x1),
      _4725: x0 => x0.trustedTypes,
      _4726: (x0,x1) => { x0.text = x1 },
      _4727: o => o instanceof Array,
      _4728: (a, i) => a.push(i),
      _4731: (a, l) => a.length = l,
      _4732: a => a.pop(),
      _4733: (a, i) => a.splice(i, 1),
      _4734: (a, s) => a.join(s),
      _4735: (a, s, e) => a.slice(s, e),
      _4736: (a, s, e) => a.splice(s, e),
      _4737: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _4738: a => a.length,
      _4739: (a, l) => a.length = l,
      _4740: (a, i) => a[i],
      _4741: (a, i, v) => a[i] = v,
      _4743: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _4744: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _4746: o => o instanceof Uint8Array,
      _4747: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _4748: o => o instanceof Int8Array,
      _4749: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _4750: o => o instanceof Uint8ClampedArray,
      _4751: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _4752: o => o instanceof Uint16Array,
      _4753: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _4754: o => o instanceof Int16Array,
      _4755: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _4756: o => o instanceof Uint32Array,
      _4757: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _4758: o => o instanceof Int32Array,
      _4759: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _4761: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _4762: o => o instanceof Float32Array,
      _4763: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _4764: o => o instanceof Float64Array,
      _4765: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _4766: (t, s) => t.set(s),
      _4767: l => new DataView(new ArrayBuffer(l)),
      _4768: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _4769: o => o.byteLength,
      _4770: o => o.buffer,
      _4771: o => o.byteOffset,
      _4772: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _4773: (b, o) => new DataView(b, o),
      _4774: (b, o, l) => new DataView(b, o, l),
      _4775: Function.prototype.call.bind(DataView.prototype.getUint8),
      _4776: Function.prototype.call.bind(DataView.prototype.setUint8),
      _4777: Function.prototype.call.bind(DataView.prototype.getInt8),
      _4778: Function.prototype.call.bind(DataView.prototype.setInt8),
      _4779: Function.prototype.call.bind(DataView.prototype.getUint16),
      _4780: Function.prototype.call.bind(DataView.prototype.setUint16),
      _4781: Function.prototype.call.bind(DataView.prototype.getInt16),
      _4782: Function.prototype.call.bind(DataView.prototype.setInt16),
      _4783: Function.prototype.call.bind(DataView.prototype.getUint32),
      _4784: Function.prototype.call.bind(DataView.prototype.setUint32),
      _4785: Function.prototype.call.bind(DataView.prototype.getInt32),
      _4786: Function.prototype.call.bind(DataView.prototype.setInt32),
      _4789: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _4790: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _4791: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _4792: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _4793: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _4794: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _4795: Function.prototype.call.bind(Number.prototype.toString),
      _4796: Function.prototype.call.bind(BigInt.prototype.toString),
      _4797: Function.prototype.call.bind(Number.prototype.toString),
      _4798: (d, digits) => d.toFixed(digits),
      _4838: (x0,x1) => globalThis.dmovelDownloadAsset(x0,x1),
      _4897: () => globalThis.document,
      _4903: (x0,x1) => { x0.height = x1 },
      _4905: (x0,x1) => { x0.width = x1 },
      _4907: (x0,x1) => { x0.pointerEvents = x1 },
      _4916: x0 => x0.style,
      _4919: x0 => x0.src,
      _4920: (x0,x1) => { x0.src = x1 },
      _4921: x0 => x0.naturalWidth,
      _4922: x0 => x0.naturalHeight,
      _4938: x0 => x0.status,
      _4939: (x0,x1) => { x0.responseType = x1 },
      _4941: x0 => x0.response,
      _4942: () => globalThis.dmovelGetCredential(),
      _4943: x0 => globalThis.dmovelCredentialId(x0),
      _4944: x0 => globalThis.dmovelCredentialPassword(x0),
      _4945: (x0,x1) => globalThis.dmovelStoreCredential(x0,x1),
      _4946: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._4946(f,arguments.length,x0,x1) }),
      _4947: () => globalThis.dmovelInitAutofill(),
      _4948: () => globalThis.dmovelGetPendingAutofill(),
      _4949: () => globalThis.dmovelStopAutofill(),
      _4950: (x0,x1) => globalThis.dmovelSetAutofillValues(x0,x1),
      _4951: () => globalThis.dmovelSubmitAutofillForm(),
      _4952: x0 => { globalThis.onDmovelAutofillChanged = x0 },
      _4953: x0 => x0.email,
      _4954: x0 => x0.password,
      _4955: () => globalThis.google.accounts.oauth2,
      _4957: (x0,x1) => x0.revoke(x1),
      _4958: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4958(f,arguments.length,x0) }),
      _4959: (x0,x1,x2) => x0.revoke(x1,x2),
      _4975: x0 => x0.access_token,
      _4990: () => globalThis.google.accounts.id,
      _4993: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._4993(f,arguments.length,x0) }),
      _4994: (x0,x1) => x0.prompt(x1),
      _4995: (x0,x1) => x0.renderButton(x1),
      _4996: (x0,x1,x2) => x0.renderButton(x1,x2),
      _5004: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._5004(f,arguments.length,x0) }),
      _5007: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16) => ({client_id: x0,auto_select: x1,callback: x2,login_uri: x3,native_callback: x4,cancel_on_tap_outside: x5,prompt_parent_id: x6,nonce: x7,context: x8,state_cookie_domain: x9,ux_mode: x10,allowed_parent_origin: x11,intermediate_iframe_close_callback: x12,itp_support: x13,login_hint: x14,hd: x15,use_fedcm_for_prompt: x16}),
      _5011: x0 => x0.isSkippedMoment(),
      _5012: x0 => x0.isDismissedMoment(),
      _5016: x0 => x0.getDismissedReason(),
      _5018: x0 => x0.error,
      _5020: x0 => x0.credential,
      _5023: (x0,x1,x2,x3,x4,x5,x6,x7,x8) => ({type: x0,theme: x1,size: x2,text: x3,shape: x4,logo_alignment: x5,width: x6,locale: x7,click_listener: x8}),
      _5031: x0 => { globalThis.onGoogleLibraryLoad = x0 },
      _5032: (module,f) => finalizeWrapper(f, function() { return module.exports._5032(f,arguments.length) }),
      _5083: (x0,x1) => { x0.responseType = x1 },
      _5084: x0 => x0.response,
      _5120: x0 => x0.length,
      _5159: x0 => x0.style,
      _5172: (x0,x1) => { x0.oncancel = x1 },
      _5178: (x0,x1) => { x0.onchange = x1 },
      _5218: (x0,x1) => { x0.onerror = x1 },
      _5358: (x0,x1) => { x0.nonce = x1 },
      _6088: (x0,x1) => { x0.accept = x1 },
      _6102: x0 => x0.files,
      _6128: (x0,x1) => { x0.multiple = x1 },
      _6146: (x0,x1) => { x0.type = x1 },
      _6396: (x0,x1) => { x0.src = x1 },
      _6398: (x0,x1) => { x0.type = x1 },
      _6402: (x0,x1) => { x0.async = x1 },
      _6404: (x0,x1) => { x0.defer = x1 },
      _6406: (x0,x1) => { x0.crossOrigin = x1 },
      _6408: (x0,x1) => { x0.text = x1 },
      _6410: (x0,x1) => { x0.integrity = x1 },
      _6863: () => globalThis.window,
      _6867: (x0,x1) => x0[x1],
      _6901: x0 => x0.document,
      _6904: x0 => x0.location,
      _6923: x0 => x0.navigator,
      _6927: x0 => x0.screen,
      _6939: x0 => x0.devicePixelRatio,
      _7178: x0 => x0.isSecureContext,
      _7180: x0 => x0.indexedDB,
      _7181: x0 => x0.crypto,
      _7185: x0 => x0.trustedTypes,
      _7186: x0 => x0.sessionStorage,
      _7187: x0 => x0.localStorage,
      _7197: x0 => x0.origin,
      _7206: x0 => x0.pathname,
      _7293: x0 => x0.geolocation,
      _7296: x0 => x0.mediaDevices,
      _7298: x0 => x0.permissions,
      _7299: x0 => x0.maxTouchPoints,
      _7306: x0 => x0.appCodeName,
      _7307: x0 => x0.appName,
      _7308: x0 => x0.appVersion,
      _7309: x0 => x0.platform,
      _7310: x0 => x0.product,
      _7311: x0 => x0.productSub,
      _7312: x0 => x0.userAgent,
      _7313: x0 => x0.vendor,
      _7314: x0 => x0.vendorSub,
      _7316: x0 => x0.language,
      _7317: x0 => x0.languages,
      _7318: x0 => x0.onLine,
      _7323: x0 => x0.hardwareConcurrency,
      _7362: x0 => x0.data,
      _7410: (x0,x1) => { x0.onmessage = x1 },
      _7517: x0 => x0.length,
      _9421: x0 => x0.type,
      _9422: x0 => x0.target,
      _9462: x0 => x0.signal,
      _9471: x0 => x0.length,
      _9492: x0 => x0.addedNodes,
      _9511: x0 => x0.baseURI,
      _9517: x0 => x0.firstChild,
      _9528: () => globalThis.document,
      _9609: x0 => x0.body,
      _9611: x0 => x0.head,
      _9938: x0 => x0.tagName,
      _9940: (x0,x1) => { x0.id = x1 },
      _10375: x0 => x0.ctrlKey,
      _10376: x0 => x0.shiftKey,
      _10377: x0 => x0.altKey,
      _10378: x0 => x0.metaKey,
      _11286: x0 => x0.value,
      _11288: x0 => x0.done,
      _11468: x0 => x0.size,
      _11469: x0 => x0.type,
      _11476: x0 => x0.name,
      _11477: x0 => x0.lastModified,
      _11482: x0 => x0.length,
      _11488: x0 => x0.result,
      _11985: x0 => x0.url,
      _11987: x0 => x0.status,
      _11989: x0 => x0.statusText,
      _11990: x0 => x0.headers,
      _11991: x0 => x0.body,
      _12258: x0 => x0.type,
      _12273: x0 => x0.matches,
      _12284: x0 => x0.availWidth,
      _12285: x0 => x0.availHeight,
      _12290: x0 => x0.orientation,
      _12350: x0 => x0.contentRect,
      _12376: x0 => x0.state,
      _12777: x0 => x0.active,
      _13440: x0 => x0.result,
      _13441: x0 => x0.error,
      _13446: (x0,x1) => { x0.onsuccess = x1 },
      _13448: (x0,x1) => { x0.onerror = x1 },
      _13454: x0 => x0.oldVersion,
      _13468: x0 => x0.name,
      _13470: x0 => x0.objectStoreNames,
      _13486: x0 => x0.name,
      _13488: x0 => x0.keyPath,
      _13491: x0 => x0.autoIncrement,
      _13496: x0 => x0.name,
      _13499: x0 => x0.keyPath,
      _13500: x0 => x0.multiEntry,
      _13501: x0 => x0.unique,
      _13511: x0 => x0.key,
      _13512: x0 => x0.primaryKey,
      _13514: x0 => x0.value,
      _13520: x0 => x0.error,
      _13522: (x0,x1) => { x0.onabort = x1 },
      _13524: (x0,x1) => { x0.oncomplete = x1 },
      _13526: (x0,x1) => { x0.onerror = x1 },
      _13651: x0 => x0.coords,
      _13652: x0 => x0.timestamp,
      _13654: x0 => x0.accuracy,
      _13655: x0 => x0.latitude,
      _13656: x0 => x0.longitude,
      _13657: x0 => x0.altitude,
      _13658: x0 => x0.altitudeAccuracy,
      _13659: x0 => x0.heading,
      _13660: x0 => x0.speed,
      _13661: x0 => x0.code,
      _13662: x0 => x0.message,
      _14338: (x0,x1) => { x0.cursor = x1 },
      _14348: (x0,x1) => { x0.display = x1 },
      _14512: (x0,x1) => { x0.height = x1 },
      _14724: (x0,x1) => { x0.opacity = x1 },
      _15202: (x0,x1) => { x0.width = x1 },
      _15570: x0 => x0.name,
      _15571: x0 => x0.message,
      _15574: x0 => x0.subtle,
      _15892: x0 => x0.width,
      _15893: x0 => x0.height,
      _16277: () => globalThis.console,
      _16300: () => globalThis.window.flutterCanvasKit,
      _16301: () => globalThis.window._flutter_skwasmInstance,
      _16325: () => globalThis.dmovelLoader.markFlutterReady(),
      _16326: () => globalThis.triggerPwaInstall(),
      _16327: () => globalThis.isPwaInstallAvailable(),
      _16328: () => globalThis.isPwaInstalled(),
      _16329: () => globalThis.getPwaHostPlatform(),
      _16332: x0 => x0.name,
      _16333: x0 => x0.message,
      _16334: x0 => x0.code,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
!function(){try{var e="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof globalThis?globalThis:"undefined"!=typeof self?self:{},n=(new e.Error).stack;n&&(e._sentryDebugIds=e._sentryDebugIds||{},e._sentryDebugIds[n]="c9b7999d-2f4f-55bf-b582-5a6199bcf4cf")}catch(e){}}();
//# debugId=c9b7999d-2f4f-55bf-b582-5a6199bcf4cf
